---
- hosts: all
  become: true

  tasks:
    # - name: Change directory to ruby_pinger
    - name: Build image ruby_pinger
      chdir: /var/www/Projects/ruby_pinger
      docker_image:  
        name: ruby_pinger
        build:
          # path: /var/www/Projects/ruby_pinger
          source: build
      state: present
    - name: Run container ruby_pinger
      docker_container:
        name: ruby_pinger
        image: ruby_pinger
    # - name: Change directory to cacheservice
    #   chdir: /var/www/Projects/cacheservice
    - name: Build image cacheservice
      chdir: /var/www/Projects/cacheservice
      docker_image:
        name: cacheservice
        build:
          # path: /var/www/Projects/cacheservice
          source: build
        state: present
    - name: Run container cacheservice
      docker_container: 
        name: cacheservice
        image: cacheservice
    # - name: Change directory to jager_rd
    #   chdir: /var/www/Projects/jager_rd
    # - name: Run docker-compose
    #   chdir: /var/www/Projects/jager_rd
    #   docker_compose: 
    #     project_src: /var/www/Projects/jager_rd
    #   register: output
    